global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker 容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # Bee Swarm 服务监控
  - job_name: 'bee-swarm-services'
    static_configs:
      - targets: 
        - 'pm-01:6080'
        - 'backend-01:6081'
        - 'frontend-01:6082'
        - 'qa-01:6083'
        - 'devops-01:6084'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis 监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL 监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Grafana 监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000'] 