name: Deploy AI Containers

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up environment variables
        run: |
          echo "Setting up deployment environment variables..."
          echo "DEPLOYMENT_ENV=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          
      - name: Validate deployment configuration
        run: |
          echo "🔍 Validating deployment configuration..."
          echo "Environment: ${{ inputs.environment }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          
          # 检查必要的文件
          if [ -f docker-compose.yml ]; then
            echo "✅ docker-compose.yml exists"
          else
            echo "❌ docker-compose.yml not found"
            exit 1
          fi
          
          if [ -f .env.example ]; then
            echo "✅ .env.example exists"
          else
            echo "❌ .env.example not found"
            exit 1
          fi
          
          echo "✅ Deployment configuration validation passed"
          
      - name: Deploy to production
        if: github.ref == 'refs/heads/main' && inputs.environment == 'production'
        run: |
          echo "🚀 Deploying to production environment..."
          echo "This would typically involve:"
          echo "1. SSH to production server"
          echo "2. Pull latest code from main branch"
          echo "3. Run docker-compose up -d"
          echo "4. Verify deployment health"
          echo "5. Update deployment status"
          
          # Mock deployment steps
          echo "📦 Building containers..."
          sleep 2
          echo "🔧 Starting services..."
          sleep 2
          echo "✅ Production deployment completed successfully"
          
          # Set deployment status
          echo "DEPLOYMENT_STATUS=success" >> $GITHUB_ENV
          echo "DEPLOYMENT_URL=https://production.bee-swarm.example.com" >> $GITHUB_ENV
        env:
          DEPLOYMENT_ENV: production
          
      - name: Deploy to staging
        if: inputs.environment == 'staging'
        run: |
          echo "🚀 Deploying to staging environment..."
          echo "This would typically involve:"
          echo "1. SSH to staging server"
          echo "2. Pull latest code from develop branch"
          echo "3. Run docker-compose up -d"
          echo "4. Verify deployment health"
          echo "5. Update deployment status"
          
          # Mock deployment steps
          echo "📦 Building containers..."
          sleep 2
          echo "🔧 Starting services..."
          sleep 2
          echo "✅ Staging deployment completed successfully"
          
          # Set deployment status
          echo "DEPLOYMENT_STATUS=success" >> $GITHUB_ENV
          echo "DEPLOYMENT_URL=https://staging.bee-swarm.example.com" >> $GITHUB_ENV
        env:
          DEPLOYMENT_ENV: staging
          
      - name: Verify deployment
        run: |
          echo "🔍 Verifying deployment..."
          echo "Environment: ${{ inputs.environment }}"
          echo "Deployment Time: ${{ env.DEPLOYMENT_TIME }}"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          
          # Mock health checks
          echo "🏥 Running health checks..."
          sleep 1
          echo "✅ All services are healthy"
          
          echo "📊 Deployment Summary:"
          echo "  - Status: ${{ env.DEPLOYMENT_STATUS }}"
          echo "  - URL: ${{ env.DEPLOYMENT_URL }}"
          echo "  - Environment: ${{ inputs.environment }}"
          echo "  - Commit: ${{ github.sha }}"
          
          echo "🎉 Deployment verification completed successfully"
          
      - name: Notify deployment status
        run: |
          echo "📢 Sending deployment notification..."
          echo "Deployment completed successfully!"
          echo "Environment: ${{ inputs.environment }}"
          echo "URL: ${{ env.DEPLOYMENT_URL }}"
          echo "Commit: ${{ github.sha }}"
          
          # Mock notification
          echo "✅ Deployment notification sent" 